apiVersion: v1
kind: Service
metadata:
  name: alpine-ssh
  namespace: default
spec:
  type: NodePort
  selector:
    run: alpine
  ports:
    - port: 22
      targetPort: 22
      nodePort: 30222   # You can pick any port in the 30000-32767 range