# Kubernetes Red Hat Controller (top-level)
# Supports install, uninstall, and status actions via kubernetes/ subfolder task files

- name: Kubernetes Red Hat Controller
  hosts: localhost
  become: yes
  vars:
    k8s_action: "{{ k8s_action | default('install') }}"
  vars_prompt:
    - name: "k8s_action"
      prompt: "Choose action: install, uninstall, or status"
      private: no
      default: "install"
  tasks:
    - name: Validate action
      ansible.builtin.assert:
        that:
          - k8s_action in ['install', 'uninstall', 'status']
        fail_msg: "Invalid action '{{ k8s_action }}'. Must be one of: install, uninstall, status."

    - name: Run install tasks
      ansible.builtin.include_tasks: kubernetes/k8s-redhat-kubernetes-install-tasks.yaml
      when: k8s_action == 'install'

    - name: Run uninstall tasks
      ansible.builtin.include_tasks: kubernetes/k8s-redhat-kubernetes-uninstall-tasks.yaml
      when: k8s_action == 'uninstall'

    - name: Run status tasks
      ansible.builtin.include_tasks: kubernetes/k8s-redhat-kubernetes-status-tasks.yaml
      when: k8s_action == 'status'
