---
# otel-controller.yaml
# Ansible playbook to control OTel Collector lifecycle and configuration
# Usage:
#   ansible-playbook otel-controller.yaml -e action=install -e otel_token=... -e otel_endpoint=...
#   ansible-playbook otel-controller.yaml -e action=uninstall
#   ansible-playbook otel-controller.yaml -e action=status

- hosts: localhost
  gather_facts: false
  vars:
  tasks:
    - name: Set OTel controller facts
      set_fact:
        otel_namespace: "default"
        otel_token: "{{ otel_token | default('') }}"
        otel_endpoint: "{{ otel_endpoint | default('') }}"

    - name: Run OTel install tasks
      include_tasks: otel/otel-install.yaml
      when: action == 'install'

    - name: Run OTel uninstall tasks
      include_tasks: otel/otel-uninstall.yaml
      when: action == 'uninstall'

    - name: Run OTel status tasks
      include_tasks: otel/otel-status.yaml
      when: action == 'status'
