#!/bin/bash
"""
Setup script for WindowsVM Kopf Operator
This script installs dependencies and provides instructions for running the operator
"""

echo "🚀 WindowsVM Kopf Operator Setup"
echo "================================="

# Install Python dependencies
echo "📦 Installing Python dependencies..."
pip3 install -r kopf-requirements.txt

echo ""
echo "✅ Setup completed!"
echo ""
echo "📖 Usage Instructions:"
echo "======================"
echo ""
echo "1. Run the operator locally:"
echo "   python3 kopf-manifest-controller.py"
echo ""
echo "2. In another terminal, test the operator:"
echo "   python3 test-kopf-operator.py"
echo ""
echo "3. Watch operator logs to see CR processing:"
echo "   # The operator will automatically detect WindowsVM CR changes"
echo "   # and run the corresponding Ansible playbooks"
echo ""
echo "🎯 Key Features:"
echo "• Automatic VM deployment when WindowsVM CRs are created"
echo "• VM updates when CR specs are modified"
echo "• VM cleanup when CRs are deleted"
echo "• Status monitoring and updates"
echo "• Event-driven processing with Kopf framework"
echo ""
echo "🔧 Configuration:"
echo "• CRD Group: infra.example.com"
echo "• CRD Version: v1"
echo "• Resource: windowsvms"
echo "• Namespace: default (configurable)"
echo ""
echo "📋 Operator Capabilities:"
echo "• @kopf.on.create - Handle CR creation"
echo "• @kopf.on.update - Handle CR updates" 
echo "• @kopf.on.delete - Handle CR deletion"
echo "• @kopf.timer - Monitor VM status periodically"
echo "• @kopf.on.field - React to specific field changes"
echo ""
