apiVersion: v1
kind: Pod
metadata:
  name: virtctl
  namespace: kubevirt
spec:
  containers:
  - name: shell
    image: alpine:3.19
    command: [ "sleep", "infinity" ]
    stdin: true
    tty: true
  restartPolicy: Never