apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: otelcollectors.infra.example.com
spec:
  group: infra.example.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              enabled:
                type: boolean
                description: "Enable OpenTelemetry Collector installation"
                default: true
              
              # Target Windows VM
              targetVM:
                type: object
                properties:
                  vmName:
                    type: string
                    description: "Name of the Windows VM where OTel Collector will be installed"
                  namespace:
                    type: string
                    description: "Kubernetes namespace of the target VM"
                    default: "kubevirt"
                required:
                - vmName
              
              # OpenTelemetry Configuration
              metricsType:
                type: string
                description: "Type of metrics to collect"
                enum: ["os", "mssql", "os,mssql", "mssql,os"]
                default: "os"
              
              endpoint:
                type: string
                description: "OpenTelemetry endpoint URL"
              
              token:
                type: string
                description: "Authentication token for OTel endpoint"
              
              collectorVersion:
                type: string
                description: "OpenTelemetry Collector version"
                default: "0.133.0"
              
              configPath:
                type: string
                description: "Path for otel-config.yaml on Windows VM"
                default: "C:\\Data\\otel-config.yaml"
              
              installPath:
                type: string
                description: "Installation path for OTel Collector"
                default: "C:\\Data\\otelcol"
              
              tempPath:
                type: string
                description: "Temporary download path"
                default: "C:\\Data\\temp"
              
              # Service Configuration
              serviceConfig:
                type: object
                properties:
                  serviceName:
                    type: string
                    description: "Windows service name"
                    default: "otelcollector"
                  startType:
                    type: string
                    description: "Service start type"
                    enum: ["auto", "manual", "disabled"]
                    default: "auto"
                  useScheduledTask:
                    type: boolean
                    description: "Use scheduled task if service creation fails"
                    default: true
              
              # Authentication
              credentials:
                type: object
                properties:
                  adminUser:
                    type: string
                    description: "Windows administrator username"
                    default: "Administrator"
                  adminPasswordVaultPath:
                    type: string
                    description: "Vault path for Windows admin password"
                    default: "secret/data/windows-server-2025/admin"
              
              # Prerequisites
              prerequisites:
                type: object
                properties:
                  validateWinRM:
                    type: boolean
                    description: "Validate WinRM HTTPS connectivity"
                    default: true
                  requireHTTPS:
                    type: boolean
                    description: "Require HTTPS WinRM connection"
                    default: true
                  requireMSSQLForMetrics:
                    type: boolean
                    description: "Validate MSSQL is available when collecting MSSQL metrics"
                    default: true
            
            required:
            - targetVM
            - endpoint
            - token
          
          status:
            type: object
            properties:
              phase:
                type: string
                description: "Current installation phase"
                enum: ["Pending", "Validating", "Downloading", "Installing", "Configuring", "Ready", "Failed"]
              
              lastUpdated:
                type: string
                format: date-time
              
              collectorStatus:
                type: object
                properties:
                  running:
                    type: boolean
                  pid:
                    type: string
                  runningAs:
                    type: string
                    enum: ["service", "scheduled-task", "unknown"]
                  lastChecked:
                    type: string
                    format: date-time
              
              installedVersion:
                type: string
                description: "Actually installed collector version"
              
              configType:
                type: string
                description: "Active metrics configuration type"
              
              winrmStatus:
                type: object
                properties:
                  httpsReady:
                    type: boolean
                  port:
                    type: integer
                  lastChecked:
                    type: string
                    format: date-time
                  message:
                    type: string
              
              prerequisites:
                type: object
                properties:
                  mssqlAvailable:
                    type: boolean
                    description: "MSSQL availability (when collecting MSSQL metrics)"
                  mssqlVersion:
                    type: string
                  lastChecked:
                    type: string
                    format: date-time
              
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                      enum: ["True", "False", "Unknown"]
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
              
              message:
                type: string
                description: "Human readable status message"
    
    additionalPrinterColumns:
    - name: Phase
      type: string
      description: Installation phase
      jsonPath: .status.phase
    - name: Metrics-Type
      type: string
      description: Metrics collection type
      jsonPath: .spec.metricsType
    - name: Target-VM
      type: string
      description: Target Windows VM
      jsonPath: .spec.targetVM.vmName
    - name: Running
      type: boolean
      description: Collector running
      jsonPath: .status.collectorStatus.running
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  
  scope: Namespaced
  names:
    plural: otelcollectors
    singular: otelcollector
    kind: OTelCollector
    shortNames:
    - otel
    - otlp
