# KubeVirt Controller (top-level)
# Supports install, uninstall, and status actions via kubevirt/ subfolder task files

- name: KubeVirt Controller
  hosts: localhost
  become: yes
  vars:
    # Provide concrete defaults (override with -e kubevirt_namespace=foo kubevirt_version=vX.Y.Z)
    kubevirt_namespace: "{{ kubevirt_namespace_override | default('kubevirt') }}"
    kubevirt_version: "{{ kubevirt_version_override | default('v1.3.1') }}"
  vars_prompt:
    - name: kubevirt_action
      prompt: "Choose KubeVirt action: install, uninstall, or status"
      private: no
      default: install
  tasks:
    - name: Validate action
      ansible.builtin.assert:
        that:
          - kubevirt_action in ['install', 'uninstall', 'status']
        fail_msg: "Invalid action '{{ kubevirt_action }}'. Must be one of: install, uninstall, status."

    - name: Run install tasks
      include_tasks: kubevirt/k8s-redhat-kubevirt-install-tasks.yaml
      when: kubevirt_action == 'install'

    - name: Run uninstall tasks
      include_tasks: kubevirt/k8s-redhat-kubevirt-uninstall-tasks.yaml
      when: kubevirt_action == 'uninstall'

    - name: Run status tasks
      include_tasks: kubevirt/k8s-redhat-kubevirt-status-tasks.yaml
      when: kubevirt_action == 'status'
