apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mssqlservers.infra.example.com
spec:
  group: infra.example.com
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              enabled:
                type: boolean
                description: "Enable MSSQL Server installation"
                default: true
              
              # Target Windows VM
              targetVM:
                type: object
                properties:
                  vmName:
                    type: string
                    description: "Name of the Windows VM where MSSQL will be installed"
                  namespace:
                    type: string
                    description: "Kubernetes namespace of the target VM"
                    default: "default"
                required:
                - vmName
              
              # MSSQL Configuration
              version:
                type: string
                description: "MSSQL Server version to install"
                default: "2025"
                enum: ["2019", "2022", "2025"]
              
              installerPath:
                type: string
                description: "Path to MSSQL installer on the controller"
                default: "./MS_SQL_2025.exe"
              
              installPath:
                type: string
                description: "Installation directory on Windows VM"
                default: "C:\\Data"
              
              acceptLicense:
                type: boolean
                description: "Accept SQL Server license terms"
                default: true
              
              quietInstall:
                type: boolean
                description: "Perform quiet installation"
                default: true
              
              # Authentication
              credentials:
                type: object
                properties:
                  adminUser:
                    type: string
                    description: "Windows administrator username"
                    default: "Administrator"
                  adminPasswordVaultPath:
                    type: string
                    description: "Vault path for Windows admin password"
                    default: "secret/data/windows-server-2025/admin"
                  saPasswordVaultPath:
                    type: string
                    description: "Vault path for SQL SA password"
                    default: "secret/data/windows-server-2025/admin"
              
              # Prerequisites
              prerequisites:
                type: object
                properties:
                  validateWinRM:
                    type: boolean
                    description: "Validate WinRM HTTPS connectivity"
                    default: true
                  requireHTTPS:
                    type: boolean
                    description: "Require HTTPS WinRM connection"
                    default: true
            
            required:
            - targetVM
          
          status:
            type: object
            properties:
              phase:
                type: string
                description: "Current installation phase"
                enum: ["Pending", "Validating", "Installing", "Ready", "Failed"]
              
              lastUpdated:
                type: string
                format: date-time
              
              serviceStatus:
                type: string
                description: "MSSQL Server service status"
                enum: ["Unknown", "Stopped", "Running", "Error"]
              
              installedVersion:
                type: string
                description: "Actually installed MSSQL version"
              
              installPath:
                type: string
                description: "Actual installation path"
              
              winrmStatus:
                type: object
                properties:
                  httpsReady:
                    type: boolean
                  port:
                    type: integer
                  lastChecked:
                    type: string
                    format: date-time
                  message:
                    type: string
              
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                      enum: ["True", "False", "Unknown"]
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
              
              message:
                type: string
                description: "Human readable status message"
    
    additionalPrinterColumns:
    - name: Phase
      type: string
      description: Installation phase
      jsonPath: .status.phase
    - name: Version
      type: string
      description: MSSQL version
      jsonPath: .spec.version
    - name: Target-VM
      type: string
      description: Target Windows VM
      jsonPath: .spec.targetVM.vmName
    - name: Service
      type: string
      description: Service status
      jsonPath: .status.serviceStatus
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  
  scope: Namespaced
  names:
    plural: mssqlservers
    singular: mssqlserver
    kind: MSSQLServer
    shortNames:
    - mssql
    - sql
