apiVersion: infra.example.com/v1
kind: OTelTelemetry
metadata:
  name: otel-full-stack
  namespace: default
spec:
  action: install
  componentsSummary: "collector,vault,redhat,oracle,windows,mssql"
  namespace: default
  collector:
    image: otel/opentelemetry-collector-contrib:0.133.0
    replicas: 1
  vault:
    enabled: true
    otelEndpoint: https://example.observeinc.com/v2/otel
    otelToken: VAULT_PIPELINE_TOKEN
    metricsToken: VAULT_METRICS_TOKEN
    tokenFile: /root/.vault-token
  redhat:
    enabled: true
    vmName: rhel9-vm
    namespace: default
    otelEndpoint: https://example.observeinc.com/v2/otel
    otelToken: REDHAT_PIPELINE_TOKEN
    username: redhat
    password: redhat
    metricsPort: 9100
  oracle:
    enabled: true
    vmName: rhel9-vm
    namespace: default
    otelEndpoint: https://example.observeinc.com/v2/otel
    otelToken: ORACLE_PIPELINE_TOKEN
    listenerPort: 1521
    pdbName: FREEPDB1
    metricsUsername: system
    metricsPassword: Oracle123
  windows:
    enabled: true
    vmName: windows2025
    namespace: default
    adminUsername: Administrator
    adminPasswordVaultPath: secret/data/windows-server-2025/admin
    vaultAddr: http://localhost:8200
    vaultToken: VAULT_ACCESS_TOKEN
    vaultNamespace: ""
    otelEndpoint: https://example.observeinc.com/v2/otel
    otelToken: WINDOWS_PIPELINE_TOKEN
    exporterPort: 9182
  mssql:
    enabled: true
    instanceName: MSSQLSERVER
    adminUsername: Administrator
    adminPasswordVaultPath: secret/data/windows-server-2025/admin
    saUsername: sa
    saPasswordVaultPath: secret/data/windows-server-2025/admin
    otelEndpoint: https://example.observeinc.com/v2/otel
    otelToken: MSSQL_PIPELINE_TOKEN
    windowsRef: windows2025
