apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: rhel9-vm
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: rhel9-vm
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
        resources:
          requests:
            memory: 4Gi
      volumes:
        - name: rootdisk
          containerDisk:
            image: registry.redhat.io/rhel9/rhel-guest-image@sha256:4ddcc3646842eef4ca69fcc988c7f8777a5ecb00402934cca330498afe36f095
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: rhel9-vm
              disable_root: false
              ssh_pwauth: true
              users:
                - name: redhat
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  lock_passwd: false
              chpasswd:
                list: |
                  root:redhat
                  redhat:redhat
                expire: False
              write_files:
                - path: /etc/ssh/sshd_config.d/99-cloud-init.conf
                  content: |
                    PasswordAuthentication yes
                    ChallengeResponseAuthentication no
                    UsePAM yes
              runcmd:
                - |
                  systemctl reload sshd
                - |
                  echo "==== cloud-init runcmd starting ====" | tee -a /var/log/cloudinit-debug.log
                - |
                  subscription-manager register --username=XXXXX --password=XXXX --auto-attach 2>&1 | tee -a /var/log/cloudinit-debug.log
                - |
                  subscription-manager syspurpose set-usage Development/Test 2>&1 | tee -a /var/log/cloudinit-debug.log
                - |
                  subscription-manager repos --enable=rhel-9-for-x86_64-baseos-rpms --enable=rhel-9-for-x86_64-appstream-rpms 2>&1 | tee -a /var/log/cloudinit-debug.log
                - |
                  echo "==== cloud-init runcmd finished ====" | tee -a /var/log/cloudinit-debug.log
