apiVersion: infra.example.com/v1
kind: WindowsVM
metadata:
  name: windows2025v3
  namespace: default
spec:
  # Declarative state management - no manual action editing needed
  enabled: true    # true = VM should exist and run, false = VM should not exist
  
  # VM Configuration
  image: win2025server.vhdx
  installer_disk_size: 15Gi
  kubevirt_namespace: kubevirt
  storage_dir: /data/vms
  system_disk_size: 40Gi
  vhdx_path: /data/vms/win2025server.vhdx
  virtio_iso_size: 500Mi
  vmName: windows2025v3
  vm_cpu_cores: 4
  vm_memory: 8Gi
  windows_admin_password: Secret123%%
  windows_product_key: XXXXX-XXXXX-XXXXX-XXXXX-XXXXX
  windows_version: '2025'
