apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: windowsvms.infra.example.com
spec:
  group: infra.example.com
  names:
    kind: WindowsVM
    plural: windowsvms
    singular: windowsvm
    listKind: WindowsVMList
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - vmName
                - action
                - windows_version
              properties:
                vmName:
                  type: string
                  description: Name of the VM
                action:
                  type: string
                  description: install or uninstall
                  enum: [install, uninstall]
                windows_version:
                  type: string
                  description: Windows version (2019 or 2025)
                  enum:
                    - "2019"
                    - "2025"
                image:
                  type: string
                installer_disk_size:
                  type: string
                kubevirt_namespace:
                  type: string
                storage_dir:
                  type: string
                system_disk_size:
                  type: string
                vhdx_download_url:
                  type: string
                vhdx_path:
                  type: string
                virtio_iso_size:
                  type: string
                virtio_iso_url:
                  type: string
                vm_cpu_cores:
                  type: integer
                vm_memory:
                  type: string
                windows_admin_password:
                  type: string
                windows_product_key:
                  type: string
      subresources:
        status: {}
