apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: windowsautomations.infra.example.com
spec:
  group: infra.example.com
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              enabled:
                type: boolean
                description: "Enable or disable the Windows automation"
                default: true
              
              # Target VM configuration
              targetVM:
                type: object
                properties:
                  vmName:
                    type: string
                    description: "Name of the Windows VM to automate"
                  namespace:
                    type: string
                    description: "Kubernetes namespace where the VM is deployed"
                    default: "kubevirt"
                required:
                - vmName
              
              # Prerequisites validation
              prerequisites:
                type: object
                properties:
                  validateWinRM:
                    type: boolean
                    description: "Validate WinRM HTTPS is available"
                    default: true
                  validateVMState:
                    type: boolean
                    description: "Validate VM is running and accessible"
                    default: true
                  requireHTTPS:
                    type: boolean
                    description: "Require HTTPS WinRM (no HTTP fallback)"
                    default: true
                
              # MSSQL Configuration
              mssql:
                type: object
                properties:
                  enabled:
                    type: boolean
                    description: "Enable MSSQL Server installation"
                    default: false
                  version:
                    type: string
                    description: "MSSQL Server version"
                    default: "2025"
                    enum: ["2019", "2022", "2025"]
                  installerPath:
                    type: string
                    description: "Path to MSSQL installer executable on controller"
                    default: "./MS_SQL_2025.exe"
                  installPath:
                    type: string
                    description: "Installation path on Windows VM"
                    default: "C:\\Data"
                  acceptLicense:
                    type: boolean
                    description: "Accept SQL Server license terms"
                    default: true
                  quietInstall:
                    type: boolean
                    description: "Perform quiet installation"
                    default: true
              
              # OpenTelemetry Configuration  
              otel:
                type: object
                properties:
                  enabled:
                    type: boolean
                    description: "Enable OpenTelemetry Collector installation"
                    default: false
                  metricsType:
                    type: string
                    description: "Type of metrics to collect"
                    enum: ["os", "mssql", "os,mssql", "mssql,os"]
                  endpoint:
                    type: string
                    description: "OpenTelemetry endpoint URL"
                  token:
                    type: string
                    description: "OpenTelemetry authentication token"
                  collectorVersion:
                    type: string
                    description: "OpenTelemetry Collector version"
                    default: "0.133.0"
                  configPath:
                    type: string
                    description: "Path where to store otel-config.yaml on VM"
                    default: "C:\\Data\\otel-config.yaml"
                  installPath:
                    type: string
                    description: "Installation path for OTel Collector"
                    default: "C:\\Data\\otelcol"
              
              # Credentials configuration
              credentials:
                type: object
                properties:
                  adminUser:
                    type: string
                    description: "Windows administrator username"
                    default: "Administrator"
                  vaultPath:
                    type: string
                    description: "Vault path for Windows admin password"
                    default: "secret/data/windows-server-2025/admin"
                  saPasswordVaultPath:
                    type: string
                    description: "Vault path for SQL SA password (optional)"
                    default: "secret/data/windows-server-2025/admin"
              
              # WinRM Connection settings
              winrm:
                type: object
                properties:
                  httpsPort:
                    type: integer
                    description: "HTTPS WinRM port"
                    default: 5986
                  httpPort:
                    type: integer
                    description: "HTTP WinRM port (not used with requireHTTPS)"
                    default: 5985
                  certificateValidation:
                    type: string
                    description: "Certificate validation policy"
                    enum: ["ignore", "validate"]
                    default: "ignore"
                  connectionTimeout:
                    type: integer
                    description: "Connection timeout in seconds"
                    default: 30
            
            required:
            - targetVM
          
          status:
            type: object
            properties:
              phase:
                type: string
                description: "Current phase of automation"
                enum: ["Pending", "Prerequisites", "WinRMSetup", "Installing", "Ready", "Failed"]
              
              lastUpdated:
                type: string
                format: date-time
                description: "Last status update timestamp"
              
              vmInfo:
                type: object
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                  ipAddress:
                    type: string
                  state:
                    type: string
              
              prerequisites:
                type: object
                properties:
                  winrmHTTPS:
                    type: object
                    properties:
                      ready:
                        type: boolean
                      message:
                        type: string
                      lastChecked:
                        type: string
                        format: date-time
                  vmReady:
                    type: object
                    properties:
                      ready:
                        type: boolean
                      message:
                        type: string
                      lastChecked:
                        type: string
                        format: date-time
              
              mssql:
                type: object
                properties:
                  installed:
                    type: boolean
                  serviceStatus:
                    type: string
                  version:
                    type: string
                  installPath:
                    type: string
                  lastChecked:
                    type: string
                    format: date-time
                  message:
                    type: string
              
              otel:
                type: object
                properties:
                  installed:
                    type: boolean
                  collectorRunning:
                    type: boolean
                  version:
                    type: string
                  pid:
                    type: string
                  configType:
                    type: string
                  lastChecked:
                    type: string
                    format: date-time
                  message:
                    type: string
              
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                      enum: ["True", "False", "Unknown"]
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
              
              message:
                type: string
                description: "Human readable status message"
              
              observedGeneration:
                type: integer
                description: "Last observed generation of the resource"
    
    additionalPrinterColumns:
    - name: Phase
      type: string
      description: Current automation phase
      jsonPath: .status.phase
    - name: VM
      type: string
      description: Target VM name
      jsonPath: .spec.targetVM.vmName
    - name: MSSQL
      type: boolean
      description: MSSQL enabled
      jsonPath: .spec.mssql.enabled
    - name: OTel
      type: boolean  
      description: OpenTelemetry enabled
      jsonPath: .spec.otel.enabled
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  
  scope: Namespaced
  names:
    plural: windowsautomations
    singular: windowsautomation
    kind: WindowsAutomation
    shortNames:
    - winautom
    - wa
