# OpenTelemetry Collector Custom Resource - Combined OS and MSSQL metrics
apiVersion: infra.example.com/v1
kind: WindowsOTelCollector
metadata:
  name: win2025-otel-collector
  namespace: default
spec:
  targetVM:
    vmName: "win2025server"
    namespace: "default"
  metricsType: "os,mssql"  # Collect both OS and MSSQL metrics
  endpoint: "https://your-otel-endpoint.com/v2/otel"
  token: "your-otel-token"
  collectorVersion: "0.133.0"
  configPath: "C:\\Data\\otel-config.yaml"
  installPath: "C:\\Data\\otelcol"
  tempPath: "C:\\Data\\temp"
  serviceConfig:
    serviceName: "windowsotelcollector"
    startType: "auto"
    useScheduledTask: true
  credentials:
    adminUser: "Administrator"
    adminPasswordVaultPath: "secret/data/windows-server-2025/admin"
  prerequisites:
    validateWinRM: true
    requireHTTPS: true
    requireMSSQLForMetrics: true  # Validate MSSQL since we're collecting MSSQL metrics
