 - name: Get Vault pod(s) status
   kubernetes.core.k8s_info:
     api_version: v1
     kind: Pod
     namespace: "vault"
     label_selectors:
       - "app=vault"
   register: vault_pods

 - name: Show Vault pod status and CLI usage
   ansible.builtin.debug:
     msg: |
       {% if vault_pods.resources|length == 0 %}
       No Vault pods found in namespace 'vault'.
       {% else %}
       {% for pod in vault_pods.resources %}
       Pod: {{ pod.metadata.name }} | Phase: {{ pod.status.phase }} | Ready: {{ pod.status.containerStatuses[0].ready | default('N/A') }}
       {% endfor %}
       {% endif %}

       Vault CLI usage (with port-forward running):
         export VAULT_ADDR=http://127.0.0.1:8200
         vault login root
         vault kv get -field=password secret/myapp/admin
      
