 - name: Delete Vault manifest
   ansible.builtin.shell: |
     kubectl delete -f vault-hashicorp/vault-hashicorp-manifest.yaml --ignore-not-found

 - name: Delete Vault namespace
   ansible.builtin.shell: |
     kubectl delete namespace vault --ignore-not-found

 - name: Kill any port-forward processes for Vault
   ansible.builtin.shell: |
     pkill -f "kubectl.*port-forward.*8200" || true
   ignore_errors: true

 - name: Confirm Vault uninstall complete
   ansible.builtin.debug:
     msg: "Vault and all related resources have been removed from the cluster."
  
