apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ansible-operator-role
  namespace: default
rules:
- apiGroups: ["infra.example.com"]
  resources: ["windowsvms"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["infra.example.com"]
  resources: ["windowsvms/status"]
  verbs: ["update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ansible-operator-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: ansible-operator-role
  apiGroup: rbac.authorization.k8s.io