---
- name: Uninstall Vault Helm release
  ansible.builtin.shell: helm uninstall vault -n default
  ignore_errors: true

- name: Delete Vault PVCs in default namespace
  ansible.builtin.shell: |
    kubectl delete pvc -n default -l app.kubernetes.io/name=vault
  ignore_errors: true

- name: Delete Vault services in default namespace
  ansible.builtin.shell: |
    kubectl delete svc -n default -l app.kubernetes.io/name=vault
  ignore_errors: true

- name: Delete Vault secrets in default namespace
  ansible.builtin.shell: |
    kubectl delete secret -n default -l app.kubernetes.io/name=vault
  ignore_errors: true

- name: Delete Vault configmaps in default namespace
  ansible.builtin.shell: |
    kubectl delete configmap -n default -l app.kubernetes.io/name=vault
  ignore_errors: true
